stages:
  - test
  - integration_test

test:
  stage: test
  image: golang
  before_script:
    - go mod download
  script:
    - go test -v -race ./...
  when: manual

linter:
  stage: test
  image: golangci/golangci-lint:v1.55.2
  before_script:
    - go mod download
  script:
    - golangci-lint run ./...
  when: manual

integration test:
  stage: integration_test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk --no-cache add curl    
  script:
    #- sh ./run_integration_test.sh
    - docker compose up &
    - sleep 45
    - |
      curl --request POST \
        --url http://127.0.0.1:8181/onos/v1/applications/org.onosproject.fwd/active \
        --header 'Accept: application/json' \
        --header 'Authorization: Basic b25vczpyb2Nrcw=='
    - |
      curl --request POST \
        --url http://127.0.0.1:8181/onos/v1/applications/org.onosproject.openflow/active \
        --header 'Accept: application/json' \
        --header 'Authorization: Basic b25vczpyb2Nrcw=='
    - docker exec -it mininet /bin/bash
    - mn --topo tree,2,2 --mac --switch ovs,protocols=OpenFlow14	  --controller remote,ip=onos
  after_script:
    - docker compose stop
  when: manual