stages:
  - test
  - build

test:
  stage: test
  image: golang
  before_script:
    - go mod download
  script:
    - go test -v -race ./...
  when: manual

linter:
  stage: test
  image: golangci/golangci-lint:v1.55.2
  before_script:
    - go mod download
  script:
    - golangci-lint run ./...
  when: manual

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apt-get install mininet  
    - docker pull onosproject/onos:2.7-latest
    - docker run -t -d -p 8181:8181 -p 8101:8101 -p 5005:5005 -p 830:830 -p 9876:9876 -p 6653:6653 -p 6640:6640 --name onos onosproject/onos:2.7-latest
    - |
      curl --request POST \
      --url http://localhost:8181/onos/v1/applications/org.onosproject.fwd/active \
      --header 'Accept: application/json' \
      --header 'Authorization: Basic b25vczpyb2Nrcw=='
    - |
      curl --request POST \
      --url http://localhost:8181/onos/v1/applications/org.onosproject.openflow/active \
      --header 'Accept: application/json' \
      --header 'Authorization: Basic b25vczpyb2Nrcw=='    
  script:
    - mn --topo tree,2,2 --mac --switch ovs,protocols=OpenFlow14  --controller remote,ip=127.0.0.1




