stages:
  - test
  - build

test:
  stage: test
  image: golang
  before_script:
    - go mod download
  script:
    - go test -v -race ./...
  when: manual

linter:
  stage: test
  image: golangci/golangci-lint:v1.55.2
  before_script:
    - go mod download
  script:
    - golangci-lint run ./...
  when: manual
