stages:
  - test
  - integration_test

test:
  stage: test
  image: golang
  before_script:
    - go mod download
  script:
    - go test -v -race ./...
  when: manual

linter:
  stage: test
  image: golangci/golangci-lint:v1.55.2
  before_script:
    - go mod download
  script:
    - golangci-lint run ./...
  when: manual

integration test:
  stage: integration_test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk --no-cache add curl    
  script:
    - sh ./run_integration_test.sh
  after_script:
    - docker compose stop
  when: manual