stages:
  - test
  - build

test:
  stage: test
  image: golang
  before_script:
    - go mod download
  script:
    - go test -v -race ./...
  when: manual

linter:
  stage: test
  image: golangci/golangci-lint:v1.55.2
  before_script:
    - go mod download
  script:
    - golangci-lint run ./...
  when: manual

build:
  stage: build
  image: 
    name: ctjnkns/onos-mininet:0.1.0
    entrypoint: [""]
  before_script:
    - echo "Before Script!"
    - cd /root
    - pwd
    - whoami
    - /root/onos/bin/onos-service server 2>1 &   
    - sleep 30 
    - |
      curl --request POST \
      --url http://localhost:8181/onos/v1/applications/org.onosproject.fwd/active \
      --header 'Accept: application/json' \
      --header 'Authorization: Basic b25vczpyb2Nrcw=='
    - |
      curl --request POST \
      --url http://localhost:8181/onos/v1/applications/org.onosproject.openflow/active \
      --header 'Accept: application/json' \
      --header 'Authorization: Basic b25vczpyb2Nrcw=='
  script:
    - mn --topo tree,2,2 --mac --switch ovs,protocols=OpenFlow14  --controller remote,ip=127.0.0.1

