image: golang

stages:
  - test

test:
  stage: test
  before_script:
    - go mod download
  script:
    - go test -race ./...

linter:
  stage: test
  image: golangci/golangci-lint:v1.50.1
  before_script:
    - go mod download
  script:
    - golangci-lint run ./...
